# Generated by Django 5.2.7 on 2025-10-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="job_role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
