# Generated by Django 5.2.7 on 2025-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_job_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notification_preference",
            field=models.CharField(
                choices=[
                    ("all", "All Notifications"),
                    ("company", "Company Only"),
                    ("none", "None"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="send_public_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
