# Generated by Django 5.2.7 on 2025-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_notification_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="contrast_level",
            field=models.CharField(
                choices=[
                    ("normal", "Normal Contrast"),
                    ("high", "High Contrast"),
                    ("higher", "Higher Contrast"),
                    ("highest", "Highest Contrast"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="keyboard_navigation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="screen_reader",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light Theme"),
                    ("dark", "Dark Theme"),
                    ("standard", "Standard Theme"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
