# Generated by Django 5.2.7 on 2025-10-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_contrast_level_customuser_font_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contrast_level",
            field=models.CharField(
                choices=[
                    ("low", "Low Contrast"),
                    ("normal", "Normal Contrast"),
                    ("high", "High Contrast"),
                    ("highest", "Highest Contrast"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="keyboard_navigation",
            field=models.BooleanField(default=True),
        ),
    ]
