# Generated by Django 5.2.7 on 2025-10-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_contrast_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="birth_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(default="Not Specified", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("not_preferred", "Prefer not to say"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default="Not Specified", max_length=20),
            preserve_default=False,
        ),
    ]
