# Generated by Django 5.2.7 on 2025-10-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_birth_day_customuser_birth_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="show_address",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_age",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_gender",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_marital_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_phone",
            field=models.BooleanField(default=True),
        ),
    ]
