# Generated by Django 5.2.7 on 2025-10-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_show_address_customuser_show_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="contrast_level",
        ),
        migrations.AddField(
            model_name="customuser",
            name="brightness_level",
            field=models.CharField(
                choices=[
                    ("low", "Low Brightness"),
                    ("normal", "Normal Brightness"),
                    ("high", "High Brightness"),
                    ("highest", "Highest Brightness"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="high_contrast",
            field=models.BooleanField(default=False),
        ),
    ]
