name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run tests
        working-directory: ./frontend
        run: npm test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: 'test-secret-key-for-ci-only-do-not-use-in-production'
      DEBUG: 'True'
      DB_NAME: 'test_db'
      DB_USER: 'test_user'
      DB_PASSWORD: 'test_password'
      DB_HOST: 'localhost'
      DB_PORT: '5432'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest pytest-django
      
      - name: Run tests
        run: pytest tests/ -v --tb=short
